services:
  catalog:
    build:
      context: ./services/catalog
    environment:
      - PORT=8081
      - VERSION=compose
    ports:
      - "8081:8081"

  order:
    build:
      context: ./services/order
    environment:
      - PORT=8082
      - VERSION=compose
      - CATALOG_URL=http://catalog:8081
    ports:
      - "8082:8082"
    depends_on:
      - catalog
